### PR TITLE
Dinner recipe.md

### PR DESCRIPTION
**Pull request by amarisskim1**
## 🎯 Objective

Dinner recipe - initial version

## 🛠️ Changes made

everything

## 👥 Who needs to review this Pull Request? 
@frankzhang95 @nyhdo93 @eliasmufa

### CODE REVIEW

**Comment by nyhdo93** [comment]
Awesome will review now

**Comment by frankzhang95** [comment]
Thanks Amariss, will make changes now!

**Review by amarisskim1 — COMMENTED** [review]
Great tip

**Review by amarisskim1 — COMMENTED** [review]
Looks great thanks!

**Comment by nyhdo93** [comment]
Approved!

**Review by frankzhang95 — APPROVED** [review]
Approved!

**Review by frankzhang95 — APPROVED** [review]
approving this change as well

**Pull request merged**
